var TYPICAL = [
  {cat:'Крупы и гарниры', items:[
    {name:'Гречка',        unit:'g',   per:90},
    {name:'Рис',           unit:'g',   per:90},
    {name:'Пшено',         unit:'g',   per:90},
    {name:'Булгур',        unit:'g',   per:90},
    {name:'Кускус',        unit:'g',   per:70},
    {name:'Макароны',      unit:'g',   per:110},
    {name:'Лапша',         unit:'g',   per:90},
    {name:'Овсянка',       unit:'g',   per:60},
    {name:'Манка',         unit:'g',   per:50},
    {name:'Картофель сушёный', unit:'g', per:40},
  ]},
  {cat:'Мясо и рыба', items:[
    {name:'Тушёнка',       unit:'g',   per:125},
    {name:'Сублиматы мясные', unit:'g', per:40},
    {name:'Колбаса/салями', unit:'g',  per:60},
    {name:'Сало',          unit:'g',   per:40},
    {name:'Рыба консерв.',    unit:'g',   per:125},
    {name:'Сосиски',       unit:'g',   per:100},
  ]},
  {cat:'Молочка и жиры', items:[
    {name:'Сыр',           unit:'g',   per:40},
    {name:'Масло сливочное', unit:'g', per:15},
    {name:'Масло растит.', unit:'g',   per:15},
    {name:'Сухое молоко',  unit:'g',   per:20},
    {name:'Сгущёнка',      unit:'g',   per:40},
    {name:'Сметана сухая', unit:'g',   per:15},
  ]},
  {cat:'Овощи и зелень', items:[
    {name:'Лук',           unit:'g',   per:30},
    {name:'Чеснок',        unit:'g',   per:7},
    {name:'Морковь',       unit:'g',   per:50},
    {name:'Томатная паста', unit:'g',  per:20},
  ]},
  {cat:'Хлеб и супы', items:[
    {name:'Хлеб',          unit:'g',   per:70},
    {name:'Сухари',        unit:'g',   per:50},
    {name:'Лаваш',         unit:'g',   per:60},
    {name:'Суп пакет.',    unit:'g',   per:50},
  ]},
  {cat:'Напитки', items:[
    {name:'Чай',           unit:'g',   per:5},
    {name:'Кофе',          unit:'g',   per:6},
    {name:'Какао',         unit:'g',   per:20},
    {name:'Цикорий',       unit:'g',   per:5},
    {name:'Кисель',        unit:'g',   per:20},
  ]},
  {cat:'Сладкое', items:[
    {name:'Сахар',         unit:'g',   per:25},
    {name:'Шоколад',       unit:'g',   per:30},
    {name:'Конфеты',       unit:'g',   per:40},
    {name:'Печенье',       unit:'g',   per:50},
    {name:'Сушки/баранки', unit:'g',   per:40},
    {name:'Халва',         unit:'g',   per:40},
    {name:'Козинаки',      unit:'g',   per:40},
    {name:'Мармелад',      unit:'g',   per:30},
    {name:'Мёд',           unit:'g',   per:25},
  ]},
  {cat:'Перекус', items:[
    {name:'Орехи',         unit:'g',   per:30},
    {name:'Сухофрукты',    unit:'g',   per:30},
    {name:'Батончик мюсли', unit:'pcs', per:1},
    {name:'Шоколад. батончик', unit:'pcs', per:1},
    {name:'Ириски',        unit:'g',   per:30},
    {name:'Курага',        unit:'g',   per:30},
    {name:'Изюм',          unit:'g',   per:30},
  ]},
  {cat:'Специи и прочее', items:[
    {name:'Соль',          unit:'g',   per:4},
    {name:'Специи',        unit:'g',   per:2},
    {name:'Лимонная кислота', unit:'g', per:1},
    {name:'Лавровый лист', unit:'pcs', per:1},
  ]},
];